import { db } from '..'; 
import { componentsTable } from '../schema/components';

const seeder = async () => {

  const components = [
    {
      name: 'Intel Core i9-11900K',
      type: 'processor',
      brand: 'Intel',
      model: 'Core i9-11900K',
      releaseDate: new Date('2021-03-16'),
      specifications: {
        socketType: 'LGA1200',
        coreCount: 8,
        threadCount: 16,
        baseClock: 3.5,
        boostClock: 5.3,
        tdp: 125,
      },
    },
    {
      name: 'AMD Ryzen 9 5900X',
      type: 'processor',
      brand: 'AMD',
      model: 'Ryzen 9 5900X',
      releaseDate: new Date('2020-11-05'),
      specifications: {
        socketType: 'AM4',
        coreCount: 12,
        threadCount: 24,
        baseClock: 3.7,
        boostClock: 4.8,
        tdp: 105,
      },
    },
    {
      name: 'Intel Pentium 4 1.4 GHz',
      type: 'processor',
      brand: 'Intel',
      model: 'Pentium 4 1.4 GHz',
      releaseDate: new Date('2000-11-20'),
      specifications: {
        socketType: 'Socket 423',
        coreCount: 1,
        threadCount: 1,
        baseClock: 1.4,
        boostClock: 1.4,
        tdp: 55,
      },
    },
    {
      name: 'AMD Athlon 64 3000+',
      type: 'processor',
      brand: 'AMD',
      model: 'Athlon 64 3000+',
      releaseDate: new Date('2003-09-23'),
      specifications: {
        socketType: 'Socket 754',
        coreCount: 1,
        threadCount: 1,
        baseClock: 2.0,
        boostClock: 2.0,
        tdp: 89,
      },
    },
    {
      name: 'Intel Core 2 Duo E8400',
      type: 'processor',
      brand: 'Intel',
      model: 'Core 2 Duo E8400',
      releaseDate: new Date('2008-01-20'),
      specifications: {
        socketType: 'LGA775',
        coreCount: 2,
        threadCount: 2,
        baseClock: 3.0,
        boostClock: 3.6,
        tdp: 65,
      },
    },
    {
      name: 'AMD Ryzen 5 1600',
      type: 'processor',
      brand: 'AMD',
      model: 'Ryzen 5 1600',
      releaseDate: new Date('2017-03-02'),
      specifications: {
        socketType: 'AM4',
        coreCount: 6,
        threadCount: 12,
        baseClock: 3.2,
        boostClock: 3.6,
        tdp: 65,
      },
    },
    {
      name: 'Intel Core i7-7700K',
      type: 'processor',
      brand: 'Intel',
      model: 'Core i7-7700K',
      releaseDate: new Date('2017-01-05'),
      specifications: {
        socketType: 'LGA1151',
        coreCount: 4,
        threadCount: 8,
        baseClock: 4.2,
        boostClock: 4.5,
        tdp: 91,
      },
    },
    {
      name: 'ASUS ROG Strix Z590-E',
      type: 'motherboard',
      brand: 'ASUS',
      model: 'ROG Strix Z590-E',
      releaseDate: new Date('2021-01-27'),
      specifications: {
        socketType: 'LGA1200',
        chipset: 'Z590',
        formFactor: 'ATX',
        maxMemory: 128,
        memorySlots: 4,
      },
    },
    {
      name: 'MSI MPG B550 Gaming Edge WiFi',
      type: 'motherboard',
      brand: 'MSI',
      model: 'MPG B550 Gaming Edge WiFi',
      releaseDate: new Date('2020-06-16'),
      specifications: {
        socketType: 'AM4',
        chipset: 'B550',
        formFactor: 'ATX',
        maxMemory: 128,
        memorySlots: 4,
      },
    },
    {
      name: 'ASUS P4T',
      type: 'motherboard',
      brand: 'ASUS',
      model: 'P4T',
      releaseDate: new Date('2000-12-01'),
      specifications: {
        socketType: 'Socket 423',
        chipset: 'Intel 850',
        formFactor: 'ATX',
        maxMemory: 2048,
        memorySlots: 4,
      },
    },
    {
      name: 'MSI K8N Neo2 Platinum',
      type: 'motherboard',
      brand: 'MSI',
      model: 'K8N Neo2 Platinum',
      releaseDate: new Date('2004-07-01'),
      specifications: {
        socketType: 'Socket 939',
        chipset: 'nVIDIA nForce3 Ultra',
        formFactor: 'ATX',
        maxMemory: 4096,
        memorySlots: 4,
      },
    },
    {
      name: 'Gigabyte Z390 Aorus Ultra',
      type: 'motherboard',
      brand: 'Gigabyte',
      model: 'Z390 Aorus Ultra',
      releaseDate: new Date('2018-11-13'),
      specifications: {
        socketType: 'LGA1151',
        chipset: 'Z390',
        formFactor: 'ATX',
        maxMemory: 64,
        memorySlots: 4,
      },
    },
    {
      name: 'ASRock B450M Pro4',
      type: 'motherboard',
      brand: 'ASRock',
      model: 'B450M Pro4',
      releaseDate: new Date('2018-08-01'),
      specifications: {
        socketType: 'AM4',
        chipset: 'B450',
        formFactor: 'MicroATX',
        maxMemory: 64,
        memorySlots: 4,
      },
    },
    {
      name: 'Corsair Vengeance LPX 16GB',
      type: 'ram',
      brand: 'Corsair',
      model: 'Vengeance LPX',
      releaseDate: new Date('2018-06-19'),
      specifications: {
        memoryType: 'DDR4',
        capacity: 16,
        speed: 3200,
        latency: 16,
      },
    },
    {
      name: 'G.SKILL Trident Z Royal 32GB',
      type: 'ram',
      brand: 'G.SKILL',
      model: 'Trident Z Royal',
      releaseDate: new Date('2019-03-15'),
      specifications: {
        memoryType: 'DDR4',
        capacity: 32,
        speed: 3600,
        latency: 18,
      },
    },
    {
      name: 'Kingston ValueRAM 512MB DDR-266',
      type: 'ram',
      brand: 'Kingston',
      model: 'ValueRAM 512MB DDR-266',
      releaseDate: new Date('2001-07-01'),
      specifications: {
        memoryType: 'DDR',
        capacity: 512,
        speed: 266,
        latency: 2.5,
      },
    },
    {
      name: 'G.SKILL Ripjaws V Series 16GB DDR4-3200',
      type: 'ram',
      brand: 'G.SKILL',
      model: 'Ripjaws V Series',
      releaseDate: new Date('2015-07-01'),
      specifications: {
        memoryType: 'DDR4',
        capacity: 16,
        speed: 3200,
        latency: 16,
      },
    },
    {
      name: 'Corsair Dominator Platinum 32GB DDR4-3600',
      type: 'ram',
      brand: 'Corsair',
      model: 'Dominator Platinum',
      releaseDate: new Date('2019-11-01'),
      specifications: {
        memoryType: 'DDR4',
        capacity: 32,
        speed: 3600,
        latency: 18,
      },
    },
    {
      name: 'Crucial Ballistix 8GB DDR4-2666',
      type: 'ram',
      brand: 'Crucial',
      model: 'Ballistix',
      releaseDate: new Date('2016-05-01'),
      specifications: {
        memoryType: 'DDR4',
        capacity: 8,
        speed: 2666,
        latency: 16,
      },
    },
    {
      name: 'Corsair RM850x',
      type: 'powersupply',
      brand: 'Corsair',
      model: 'RM850x',
      releaseDate: new Date('2020-01-01'),
      specifications: {
        wattage: 850,
        efficiency: '80+ Gold',
        modular: true,
      },
    },
    {
      name: 'EVGA SuperNOVA 750 G5',
      type: 'powersupply',
      brand: 'EVGA',
      model: 'SuperNOVA 750 G5',
      releaseDate: new Date('2019-11-01'),
      specifications: {
        wattage: 750,
        efficiency: '80+ Gold',
        modular: true,
      },
    },
    {
      name: 'Antec TruePower 480W',
      type: 'powersupply',
      brand: 'Antec',
      model: 'TruePower 480W',
      releaseDate: new Date('2004-05-01'),
      specifications: {
        wattage: 480,
        efficiency: '80+ Bronze',
        modular: false,
      },
    },
    {
      name: 'Thermaltake Toughpower Grand 1200W',
      type: 'powersupply',
      brand: 'Thermaltake',
      model: 'Toughpower Grand 1200W',
      releaseDate: new Date('2012-03-01'),
      specifications: {
        wattage: 1200,
        efficiency: '80+ Gold',
        modular: true,
      },
    },
    {
      name: 'Seasonic Focus GX-750',
      type: 'powersupply',
      brand: 'Seasonic',
      model: 'Focus GX-750',
      releaseDate: new Date('2020-08-01'),
      specifications: {
        wattage: 750,
        efficiency: '80+ Gold',
        modular: true,
      },
    },
    {
      name: 'Cooler Master V750',
      type: 'powersupply',
      brand: 'Cooler Master',
      model: 'V750',
      releaseDate: new Date('2015-09-01'),
      specifications: {
        wattage: 750,
        efficiency: '80+ Gold',
        modular: true,
      },
    },
    {
      name: 'NVIDIA GeForce RTX 3080',
      type: 'vga',
      brand: 'NVIDIA',
      model: 'GeForce RTX 3080',
      releaseDate: new Date('2020-09-17'),
      specifications: {
        memorySize: 10,
        memoryType: 'GDDR6X',
        coreClock: 1440,
        boostClock: 1710,
      },
    },
    {
      name: 'AMD Radeon RX 6800 XT',
      type: 'vga',
      brand: 'AMD',
      model: 'Radeon RX 6800 XT',
      releaseDate: new Date('2020-11-18'),
      specifications: {
        memorySize: 16,
        memoryType: 'GDDR6',
        coreClock: 1825,
        boostClock: 2250,
      },
    },
    {
      name: 'ATI Radeon 9700 Pro',
      type: 'vga',
      brand: 'ATI',
      model: 'Radeon 9700 Pro',
      releaseDate: new Date('2002-08-01'),
      specifications: {
        memorySize: 128,
        memoryType: 'DDR',
        coreClock: 325,
        boostClock: 325,
      },
    },
    {
      name: 'NVIDIA GeForce GTX 8800 Ultra',
      type: 'vga',
      brand: 'NVIDIA',
      model: 'GeForce GTX 8800 Ultra',
      releaseDate: new Date('2007-03-01'),
      specifications: {
        memorySize: 768,
        memoryType: 'GDDR3',
        coreClock: 612,
        boostClock: 648,
      },
    },
    {
      name: 'NVIDIA GeForce GTX 1080 Ti',
      type: 'vga',
      brand: 'NVIDIA',
      model: 'GeForce GTX 1080 Ti',
      releaseDate: new Date('2017-03-10'),
      specifications: {
        memorySize: 11,
        memoryType: 'GDDR5X',
        coreClock: 1480,
        boostClock: 1582,
      },
    },
    {
      name: 'AMD Radeon RX 5700 XT',
      type: 'vga',
      brand: 'AMD',
      model: 'Radeon RX 5700 XT',
      releaseDate: new Date('2019-07-07'),
      specifications: {
        memorySize: 8,
        memoryType: 'GDDR6',
        coreClock: 1605,
        boostClock: 1905,
      },
    },
    {
      name: 'Noctua NF-A12x25',
      type: 'fan',
      brand: 'Noctua',
      model: 'NF-A12x25',
      releaseDate: new Date('2018-05-01'),
      specifications: {
        size: 120,
        rpm: 2000,
        airflow: 60.1,
        noiseLevel: 22.6,
      },
    },
    {
      name: 'Corsair LL120 RGB',
      type: 'fan',
      brand: 'Corsair',
      model: 'LL120 RGB',
      releaseDate: new Date('2017-09-01'),
      specifications: {
        size: 120,
        rpm: 1500,
        airflow: 43.25,
        noiseLevel: 24.8,
      },
    },
    // Data tambahan
    {
      name: 'Thermaltake Riing 12',
      type: 'fan',
      brand: 'Thermaltake',
      model: 'Riing 12',
      releaseDate: new Date('2015-06-01'),
      specifications: {
        size: 120,
        rpm: 1500,
        airflow: 48.6,
        noiseLevel: 25.2,
      },
    },
    {
      name: 'be quiet! Silent Wings 3',
      type: 'fan',
      brand: 'be quiet!',
      model: 'Silent Wings 3',
      releaseDate: new Date('2016-05-01'),
      specifications: {
        size: 120,
        rpm: 1450,
        airflow: 50.5,
        noiseLevel: 16.4,
      },
    },
    {
      name: 'Arctic P12',
      type: 'fan',
      brand: 'Arctic',
      model: 'P12',
      releaseDate: new Date('2019-10-01'),
      specifications: {
        size: 120,
        rpm: 2000,
        airflow: 56.3,
        noiseLevel: 25.5,
      },
    },
    {
      name: 'Cooler Master MasterFan MF120R',
      type: 'fan',
      brand: 'Cooler Master',
      model: 'MasterFan MF120R',
      releaseDate: new Date('2018-03-01'),
      specifications: {
        size: 120,
        rpm: 2000,
        airflow: 65.5,
        noiseLevel: 33.5,
      },
    },
  ]

  try {
    for (const component of components) {
      await db.insert(componentsTable).values(component);
    }
    console.log('Components seeder completed!');
  } catch (error) {
    console.error('Components seeder failed:', error);
  }
};

seeder();
